[2022-11-29T11:13:02.322+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: twitter_etl.extract manual__2022-11-29T11:12:00.156597+00:00 [queued]>
[2022-11-29T11:13:02.334+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: twitter_etl.extract manual__2022-11-29T11:12:00.156597+00:00 [queued]>
[2022-11-29T11:13:02.334+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T11:13:02.334+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-11-29T11:13:02.334+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T11:13:02.354+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): extract> on 2022-11-29 11:12:00.156597+00:00
[2022-11-29T11:13:02.358+0000] {standard_task_runner.py:55} INFO - Started process 296 to run task
[2022-11-29T11:13:02.360+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitter_etl', 'extract', 'manual__2022-11-29T11:12:00.156597+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dags.py', '--cfg-path', '/tmp/tmp82kwvnsi']
[2022-11-29T11:13:02.361+0000] {standard_task_runner.py:83} INFO - Job 34: Subtask extract
[2022-11-29T11:13:02.423+0000] {task_command.py:376} INFO - Running <TaskInstance: twitter_etl.extract manual__2022-11-29T11:12:00.156597+00:00 [running]> on host 8cd23ebf6eb4
[2022-11-29T11:13:02.568+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=lambobr1994@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=twitter_etl
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T11:12:00.156597+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-29T11:12:00.156597+00:00
[2022-11-29T11:13:02.568+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-29T11:13:02.569+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /home/***/etl_projects/twitter/extract.py']
[2022-11-29T11:13:02.576+0000] {subprocess.py:86} INFO - Output:
[2022-11-29T11:13:02.673+0000] {subprocess.py:93} INFO - python3: can't open file '/home/***/etl_projects/twitter/extract.py': [Errno 2] No such file or directory
[2022-11-29T11:13:02.675+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2022-11-29T11:13:02.686+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-11-29T11:13:02.690+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=twitter_etl, task_id=extract, execution_date=20221129T111200, start_date=20221129T111302, end_date=20221129T111302
[2022-11-29T11:13:02.707+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 34 for task extract (Bash command failed. The command returned a non-zero exit code 2.; 296)
[2022-11-29T11:13:02.733+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-29T11:13:02.759+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
