[2022-11-29T11:38:22.204+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: twitter_etl.extract manual__2022-11-29T11:37:19.992652+00:00 [queued]>
[2022-11-29T11:38:22.212+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: twitter_etl.extract manual__2022-11-29T11:37:19.992652+00:00 [queued]>
[2022-11-29T11:38:22.213+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T11:38:22.213+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-11-29T11:38:22.213+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T11:38:22.226+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): extract> on 2022-11-29 11:37:19.992652+00:00
[2022-11-29T11:38:22.230+0000] {standard_task_runner.py:55} INFO - Started process 295 to run task
[2022-11-29T11:38:22.232+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitter_etl', 'extract', 'manual__2022-11-29T11:37:19.992652+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dags.py', '--cfg-path', '/tmp/tmp3idk67n6']
[2022-11-29T11:38:22.235+0000] {standard_task_runner.py:83} INFO - Job 53: Subtask extract
[2022-11-29T11:38:22.280+0000] {task_command.py:376} INFO - Running <TaskInstance: twitter_etl.extract manual__2022-11-29T11:37:19.992652+00:00 [running]> on host a889ea50e1ef
[2022-11-29T11:38:22.336+0000] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=lambobr1994@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=twitter_etl
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T11:37:19.992652+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-29T11:37:19.992652+00:00
[2022-11-29T11:38:22.337+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-29T11:38:22.337+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /home/***/docker/python_scripts/extract.py']
[2022-11-29T11:38:22.344+0000] {subprocess.py:86} INFO - Output:
[2022-11-29T11:38:22.451+0000] {subprocess.py:93} INFO - python3: can't open file '/home/***/docker/python_scripts/extract.py': [Errno 2] No such file or directory
[2022-11-29T11:38:22.455+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2022-11-29T11:38:22.463+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-11-29T11:38:22.466+0000] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=twitter_etl, task_id=extract, execution_date=20221129T113719, start_date=20221129T113822, end_date=20221129T113822
[2022-11-29T11:38:22.477+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 53 for task extract (Bash command failed. The command returned a non-zero exit code 2.; 295)
[2022-11-29T11:38:22.484+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-29T11:38:22.504+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
