[2022-11-29T00:13:13.394+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: twitter_etl.extract scheduled__2022-11-29T00:07:11.758931+00:00 [queued]>
[2022-11-29T00:13:13.404+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: twitter_etl.extract scheduled__2022-11-29T00:07:11.758931+00:00 [queued]>
[2022-11-29T00:13:13.404+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T00:13:13.404+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-11-29T00:13:13.404+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T00:13:13.423+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): extract> on 2022-11-29 00:07:11.758931+00:00
[2022-11-29T00:13:13.427+0000] {standard_task_runner.py:55} INFO - Started process 1712 to run task
[2022-11-29T00:13:13.429+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitter_etl', 'extract', 'scheduled__2022-11-29T00:07:11.758931+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dags.py', '--cfg-path', '/tmp/tmpzavcqurh']
[2022-11-29T00:13:13.431+0000] {standard_task_runner.py:83} INFO - Job 16: Subtask extract
[2022-11-29T00:13:13.491+0000] {task_command.py:376} INFO - Running <TaskInstance: twitter_etl.extract scheduled__2022-11-29T00:07:11.758931+00:00 [running]> on host 7edd63043531
[2022-11-29T00:13:13.581+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=lambobr1994@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=twitter_etl
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T00:07:11.758931+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-29T00:07:11.758931+00:00
[2022-11-29T00:13:13.582+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-29T00:13:13.582+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 ~/etl_projects/twitter/extract.py']
[2022-11-29T00:13:13.590+0000] {subprocess.py:86} INFO - Output:
[2022-11-29T00:13:13.685+0000] {subprocess.py:93} INFO - python3: can't open file '/home/***/etl_projects/twitter/extract.py': [Errno 2] No such file or directory
[2022-11-29T00:13:13.687+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2022-11-29T00:13:13.700+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-11-29T00:13:13.704+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=twitter_etl, task_id=extract, execution_date=20221129T000711, start_date=20221129T001313, end_date=20221129T001313
[2022-11-29T00:13:13.718+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 16 for task extract (Bash command failed. The command returned a non-zero exit code 2.; 1712)
[2022-11-29T00:13:13.722+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-29T00:13:13.751+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
