[2022-11-29T12:02:31.642+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: twitter_etl.extract scheduled__2022-11-29T11:56:29.746118+00:00 [queued]>
[2022-11-29T12:02:31.651+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: twitter_etl.extract scheduled__2022-11-29T11:56:29.746118+00:00 [queued]>
[2022-11-29T12:02:31.651+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T12:02:31.652+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-11-29T12:02:31.652+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T12:02:31.665+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): extract> on 2022-11-29 11:56:29.746118+00:00
[2022-11-29T12:02:31.669+0000] {standard_task_runner.py:55} INFO - Started process 803 to run task
[2022-11-29T12:02:31.671+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitter_etl', 'extract', 'scheduled__2022-11-29T11:56:29.746118+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dags.py', '--cfg-path', '/tmp/tmpqmt1j5e6']
[2022-11-29T12:02:31.672+0000] {standard_task_runner.py:83} INFO - Job 68: Subtask extract
[2022-11-29T12:02:31.746+0000] {task_command.py:376} INFO - Running <TaskInstance: twitter_etl.extract scheduled__2022-11-29T11:56:29.746118+00:00 [running]> on host 20e1b9fbda6e
[2022-11-29T12:02:31.835+0000] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=lambobr1994@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=twitter_etl
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T11:56:29.746118+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-29T11:56:29.746118+00:00
[2022-11-29T12:02:31.837+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-29T12:02:31.837+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /home/***/docker/python_scripts/extract.py']
[2022-11-29T12:02:31.847+0000] {subprocess.py:86} INFO - Output:
[2022-11-29T12:02:31.960+0000] {subprocess.py:93} INFO - python3: can't open file '/home/***/docker/python_scripts/extract.py': [Errno 2] No such file or directory
[2022-11-29T12:02:31.963+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2022-11-29T12:02:31.971+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-11-29T12:02:31.974+0000] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=twitter_etl, task_id=extract, execution_date=20221129T115629, start_date=20221129T120231, end_date=20221129T120231
[2022-11-29T12:02:31.987+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 68 for task extract (Bash command failed. The command returned a non-zero exit code 2.; 803)
[2022-11-29T12:02:32.004+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-29T12:02:32.024+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
