[2022-11-29T11:57:31.602+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: twitter_etl.extract scheduled__2022-11-29T11:51:29.746118+00:00 [queued]>
[2022-11-29T11:57:31.610+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: twitter_etl.extract scheduled__2022-11-29T11:51:29.746118+00:00 [queued]>
[2022-11-29T11:57:31.610+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T11:57:31.610+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-11-29T11:57:31.610+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T11:57:31.622+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): extract> on 2022-11-29 11:51:29.746118+00:00
[2022-11-29T11:57:31.626+0000] {standard_task_runner.py:55} INFO - Started process 564 to run task
[2022-11-29T11:57:31.628+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitter_etl', 'extract', 'scheduled__2022-11-29T11:51:29.746118+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dags.py', '--cfg-path', '/tmp/tmpqdc10t_b']
[2022-11-29T11:57:31.629+0000] {standard_task_runner.py:83} INFO - Job 66: Subtask extract
[2022-11-29T11:57:31.680+0000] {task_command.py:376} INFO - Running <TaskInstance: twitter_etl.extract scheduled__2022-11-29T11:51:29.746118+00:00 [running]> on host 20e1b9fbda6e
[2022-11-29T11:57:31.735+0000] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=lambobr1994@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=twitter_etl
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T11:51:29.746118+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-29T11:51:29.746118+00:00
[2022-11-29T11:57:31.736+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-29T11:57:31.737+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /home/***/docker/python_scripts/extract.py']
[2022-11-29T11:57:31.743+0000] {subprocess.py:86} INFO - Output:
[2022-11-29T11:57:31.834+0000] {subprocess.py:93} INFO - python3: can't open file '/home/***/docker/python_scripts/extract.py': [Errno 2] No such file or directory
[2022-11-29T11:57:31.837+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2022-11-29T11:57:31.846+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-11-29T11:57:31.848+0000] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=twitter_etl, task_id=extract, execution_date=20221129T115129, start_date=20221129T115731, end_date=20221129T115731
[2022-11-29T11:57:31.860+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 66 for task extract (Bash command failed. The command returned a non-zero exit code 2.; 564)
[2022-11-29T11:57:31.880+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-29T11:57:31.900+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
