[2022-11-29T11:26:30.626+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: twitter_etl.extract scheduled__2022-11-29T11:21:29.746118+00:00 [queued]>
[2022-11-29T11:26:30.635+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: twitter_etl.extract scheduled__2022-11-29T11:21:29.746118+00:00 [queued]>
[2022-11-29T11:26:30.635+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T11:26:30.635+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-11-29T11:26:30.635+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T11:26:30.651+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): extract> on 2022-11-29 11:21:29.746118+00:00
[2022-11-29T11:26:30.655+0000] {standard_task_runner.py:55} INFO - Started process 1076 to run task
[2022-11-29T11:26:30.657+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitter_etl', 'extract', 'scheduled__2022-11-29T11:21:29.746118+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dags.py', '--cfg-path', '/tmp/tmp_hqeaios']
[2022-11-29T11:26:30.658+0000] {standard_task_runner.py:83} INFO - Job 39: Subtask extract
[2022-11-29T11:26:30.710+0000] {task_command.py:376} INFO - Running <TaskInstance: twitter_etl.extract scheduled__2022-11-29T11:21:29.746118+00:00 [running]> on host 8cd23ebf6eb4
[2022-11-29T11:26:30.783+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=lambobr1994@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=twitter_etl
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T11:21:29.746118+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-29T11:21:29.746118+00:00
[2022-11-29T11:26:30.784+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-29T11:26:30.784+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /home/***/etl_projects/twitter/extract.py']
[2022-11-29T11:26:30.792+0000] {subprocess.py:86} INFO - Output:
[2022-11-29T11:26:30.883+0000] {subprocess.py:93} INFO - python3: can't open file '/home/***/etl_projects/twitter/extract.py': [Errno 2] No such file or directory
[2022-11-29T11:26:30.886+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2022-11-29T11:26:30.896+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-11-29T11:26:30.900+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=twitter_etl, task_id=extract, execution_date=20221129T112129, start_date=20221129T112630, end_date=20221129T112630
[2022-11-29T11:26:30.916+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 39 for task extract (Bash command failed. The command returned a non-zero exit code 2.; 1076)
[2022-11-29T11:26:30.949+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-29T11:26:30.976+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
