[2022-11-29T11:27:31.767+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: twitter_etl.extract scheduled__2022-11-29T11:21:29.746118+00:00 [queued]>
[2022-11-29T11:27:31.779+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: twitter_etl.extract scheduled__2022-11-29T11:21:29.746118+00:00 [queued]>
[2022-11-29T11:27:31.780+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T11:27:31.780+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-11-29T11:27:31.780+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T11:27:31.807+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): extract> on 2022-11-29 11:21:29.746118+00:00
[2022-11-29T11:27:31.810+0000] {standard_task_runner.py:55} INFO - Started process 1134 to run task
[2022-11-29T11:27:31.812+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitter_etl', 'extract', 'scheduled__2022-11-29T11:21:29.746118+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dags.py', '--cfg-path', '/tmp/tmp4lk58abi']
[2022-11-29T11:27:31.813+0000] {standard_task_runner.py:83} INFO - Job 40: Subtask extract
[2022-11-29T11:27:31.868+0000] {task_command.py:376} INFO - Running <TaskInstance: twitter_etl.extract scheduled__2022-11-29T11:21:29.746118+00:00 [running]> on host 8cd23ebf6eb4
[2022-11-29T11:27:31.940+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=lambobr1994@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=twitter_etl
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T11:21:29.746118+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-29T11:21:29.746118+00:00
[2022-11-29T11:27:31.941+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-29T11:27:31.941+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /home/***/etl_projects/twitter/extract.py']
[2022-11-29T11:27:31.949+0000] {subprocess.py:86} INFO - Output:
[2022-11-29T11:27:32.039+0000] {subprocess.py:93} INFO - python3: can't open file '/home/***/etl_projects/twitter/extract.py': [Errno 2] No such file or directory
[2022-11-29T11:27:32.041+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2022-11-29T11:27:32.051+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-11-29T11:27:32.054+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=twitter_etl, task_id=extract, execution_date=20221129T112129, start_date=20221129T112731, end_date=20221129T112732
[2022-11-29T11:27:32.068+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 40 for task extract (Bash command failed. The command returned a non-zero exit code 2.; 1134)
[2022-11-29T11:27:32.105+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-29T11:27:32.133+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
