[2022-11-29T00:50:55.426+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: twitter_etl.extract scheduled__2022-11-29T00:44:52.725755+00:00 [queued]>
[2022-11-29T00:50:55.437+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: twitter_etl.extract scheduled__2022-11-29T00:44:52.725755+00:00 [queued]>
[2022-11-29T00:50:55.437+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T00:50:55.437+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-11-29T00:50:55.437+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T00:50:55.455+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): extract> on 2022-11-29 00:44:52.725755+00:00
[2022-11-29T00:50:55.459+0000] {standard_task_runner.py:55} INFO - Started process 452 to run task
[2022-11-29T00:50:55.461+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitter_etl', 'extract', 'scheduled__2022-11-29T00:44:52.725755+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dags.py', '--cfg-path', '/tmp/tmpoi31zxa3']
[2022-11-29T00:50:55.463+0000] {standard_task_runner.py:83} INFO - Job 14: Subtask extract
[2022-11-29T00:50:55.522+0000] {task_command.py:376} INFO - Running <TaskInstance: twitter_etl.extract scheduled__2022-11-29T00:44:52.725755+00:00 [running]> on host 44d54c669ba0
[2022-11-29T00:50:55.596+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=lambobr1994@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=twitter_etl
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T00:44:52.725755+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-29T00:44:52.725755+00:00
[2022-11-29T00:50:55.597+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-29T00:50:55.597+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /home/***/docker/dags/extract.py']
[2022-11-29T00:50:55.604+0000] {subprocess.py:86} INFO - Output:
[2022-11-29T00:50:55.702+0000] {subprocess.py:93} INFO - python3: can't open file '/home/***/docker/dags/extract.py': [Errno 2] No such file or directory
[2022-11-29T00:50:55.704+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2022-11-29T00:50:55.714+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-11-29T00:50:55.718+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=twitter_etl, task_id=extract, execution_date=20221129T004452, start_date=20221129T005055, end_date=20221129T005055
[2022-11-29T00:50:55.733+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 14 for task extract (Bash command failed. The command returned a non-zero exit code 2.; 452)
[2022-11-29T00:50:55.754+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-29T00:50:55.780+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
